version: '3.8'

services:

  jobhub-db-dev:
    container_name: "jobhub-db-dev"
    hostname: "jobhub-db-dev"
    image: postgres:16-alpine
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:

  pgadmin-data:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db
